### ISSUE TITLE
Your app includes non-compliant SDK version (v4.3.0)

### ISSUE THREAD

**Issue by eLeSTRaGo63** [yandexmobile/metrica-plugin-unity#54]
Hello,

Our app now in release with AppMetrica Unity SDK 4.3.0 version and we get this message from Google Play Store

```
Your app com.application.package.name version code 21 includes SDK com.yandex.android:mobmetricalib or an SDK that one of your libraries depends on, which by default requests device location without any programmatic method to verify that end-user consent information has been obtained by the app. Apps with SDKs that collect any personal and sensitive data without disclosure and consent are in violation of Play policies.
This SDK can result in your app violating the prominent disclosure and consent and/or approved purpose requirements of Google Play's User data and Permissions and APIs that access sensitive information policies. If in violation, your app may be subject to enforcement including removal from the Play Store and new app submissions being blocked from release.
IMPORTANT: TAKE ACTION NOW TO REDUCE RISK OF VIOLATIONS
Verify that your app accesses, collects, uses and shares (including with SDKs) device location only for approved purposes and in compliance with the applicable prominent disclosure and consent requirements of the above-mentioned policies. Do not enable SDK data collection if it violates these requirements.
Even if the SDK collects device location in order to serve policy-compliant ads, the app must have a primary user-facing feature that utilises device location, which may never be acquired for the sole purpose of serving ads.
If your app meets the above-mentioned policy requirements, move to an alternative SDK or version which includes the appropriate technical mechanism to ensure that end-user consent information collected by apps is honoured.
According to the information provided by your SDK provider, you may consider upgrading to 5.0.0.
Please consult the SDK provider for further information. Google is unable to endorse or recommend any third-party software.
Here are details on how to resubmit an updated app for review. If you do not deactivate the at-risk APK, all your live APKs may be removed due to this APK.
Also, visit Google Play SDK Index for more information regarding registered SDKs, their data collection and sharing practices, and sensitive permissions used.
If you've reviewed the policy and feel that our decision may have been in error, please contact our policy support team.
```

Can you please update Android native library to latest version in Unity SDK?

Thanks.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 18149600. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp06.07.2022, 08:18, "eLeSTRaGo63" ***@***.***>:
Hello,
Our app now in release with AppMetrica Unity SDK 4.3.0 version and we get this message from Google Play Store
Your app com.application.package.name version code 21 includes SDK com.yandex.android:mobmetricalib or an SDK that one of your libraries depends on, which by default requests device location without any programmatic method to verify that end-user consent information has been obtained by the app. Apps with SDKs that collect any personal and sensitive data without disclosure and consent are in violation of Play policies.
This SDK can result in your app violating the prominent disclosure and consent and/or approved purpose requirements of Google Play's User data and Permissions and APIs that access sensitive information policies. If in violation, your app may be subject to enforcement including removal from the Play Store and new app submissions being blocked from release.
IMPORTANT: TAKE ACTION NOW TO REDUCE RISK OF VIOLATIONS
Verify that your app accesses, collects, uses and shares (including with SDKs) device location only for approved purposes and in compliance with the applicable prominent disclosure and consent requirements of the above-mentioned policies. Do not enable SDK data collection if it violates these requirements.
Even if the SDK collects device location in order to serve policy-compliant ads, the app must have a primary user-facing feature that utilises device location, which may never be acquired for the sole purpose of serving ads.
If your app meets the above-mentioned policy requirements, move to an alternative SDK or version which includes the appropriate technical mechanism to ensure that end-user consent information collected by apps is honoured.
According to the information provided by your SDK provider, you may consider upgrading to 5.0.0.
Please consult the SDK provider for further information. Google is unable to endorse or recommend any third-party software.
Here are details on how to resubmit an updated app for review. If you do not deactivate the at-risk APK, all your live APKs may be removed due to this APK.
Also, visit Google Play SDK Index for more information regarding registered SDKs, their data collection and sharing practices, and sensitive permissions used.
If you've reviewed the policy and feel that our decision may have been in error, please contact our policy support team.

Can you please update Android native library to latest version in Unity SDK?
Thanks.

**Comment by tracer8** [comment]
Any update?
This repo look like dead without support from developer.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Hello!

AppMetrica Unity SDK 5.0.0 update successfully released: https://appmetrica.yandex.com/docs/mobile-sdk-dg/plugins/unity/unity-history.html#v-5-0-0
